[bugfix] ensure that needed folder exists
cisagov/ansible-role-clamav pull request #36
Opened 2022-01-24 16:05 UTC by ClementJ35

## 🗣 Description ##

Ensure that folder exists as described in #35

2022-01-24 16:15 UTC, jsf9k requested changes
Requesting a few very minor changes.

2022-01-24 16:15 UTC, jsf9k commented on tasks/main.yml
> +    mode: '0755'
Remove unnecessary quotes:
```suggestion
    mode: 0755
```

2022-01-24 16:15 UTC, jsf9k commented on tasks/main.yml
> +    mode: '0644'
Remove unnecessary quotes:
```suggestion
    mode: 0644
```

2022-01-24 16:15 UTC, jsf9k commented on tasks/main.yml
> +- name: Ensure that log folder exist
Fix typo:
```suggestion
- name: Ensure that log folder exists
```

2022-01-25 07:42 UTC, ClementJ35 commented
As stated here : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html, the only way to create an empty file that doesn't exist is touch. Using copy or template would result in blanking the log if it exists.
But touch seems to break idempotence autobuild test.
What next ?

2022-01-25 17:49 UTC, jsf9k commented
> As stated here : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html, the only way to create an empty file that doesn't exist is touch. Using copy or template would result in blanking the log if it exists. But touch seems to break idempotence autobuild test. What next ?

You can use [`ansible.builtin.stat`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html) to determine whether you need to actually do the `touch` or not.  Let me know if you can't get it to work and I will make the change for you.

2022-01-25 17:53 UTC, jsf9k commented
@ClementJ35, thanks for the improvements to this Ansible role!

In the future, when accepting suggestions (like you did in commit 99749ef, for example) please change the default commit message to something more specific to the modifications in the commit.  For example, "Remove unnecessary quotes" would have been a good commit message for 99749ef.

Thanks again for the contribution...we appreciate it!

2022-01-25 20:54 UTC, mcdonnnj commented
@ClementJ35 Just a thought but can we use `access_time: preserve` and "modification_time: preserve` to clear idempotence while using `state: touch`?

2022-01-25 21:04 UTC, jsf9k commented
> @ClementJ35 Just a thought but can we use `access_time: preserve` and `modification_time: preserve` to clear idempotence while using `state: touch`?

This is worth a try, @ClementJ35.  This is a simpler and cleaner solution than what I suggested...if it works.

2022-01-25 21:26 UTC, jsf9k commented
I'm sorry for my name being attached to commits 5f9ba14 and 57a0a2c.  I rebased and force-pushed in order to make minor changes to the commit messages to better align with our processes, and `git` did that.  It wasn't my intent.

2022-01-25 21:28 UTC, jsf9k approved these changes

2022-01-26 07:08 UTC, mcdonnnj approved these changes
Seems reasonable enough and LGTM ✔

2022-01-26 08:21 UTC, ClementJ35 commented
Hi @jsf9k @mcdonnnj,
Those changes are fine to me. I just didn't thought about time preservation for idempotence.
@jsf9k, don't worry about my name, I don't care. I just want that role to do better.
Thanks for your responsiveness.

2022-01-26 14:47 UTC, dav3r approved these changes
Love it!  Nice improvement.  💎

2022-01-26 14:53 UTC, merged