Modify tasks to use systemd or freshclam binary
cisagov/ansible-role-clamav pull request #39
Opened 2022-01-31 16:55 UTC by ClementJ35

## 🗣 Description ##

As describe in  #38, setup based on OSes doesn't make sense now as many system use systemd.
It's better to choose using the fact : ansible_service_mgr

## 🧪 Testing ##

Tested on Debian 11 & CentOS 8

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

2022-02-02 09:07 UTC, ClementJ35 commented
Failing test seems imputable to docker instance : 
'''2022-01-31T17:01:49.4122921Z fatal: [fedora32]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\nFailed to connect to bus: Host is down\n"}'''
In the real world, Fedora 32 is systemd based.
Either ansible facts are wrong about systemd or the docker image have some ghosts information.

2022-02-04 18:34 UTC, jsf9k requested changes
Please consider my change request while I fix the failing builds.

2022-02-04 18:34 UTC, jsf9k commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
I think we should consider renaming `setup_bin.yml` to `setup_manual.yml`.  The latter more clearly indicates the purpose of the file (IMO).
```suggestion
- name: Load tasks file for manual setup
  ansible.builtin.include_tasks: setup_manual.yml
```

2022-02-04 18:56 UTC, dav3r commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
We also need to add some sort of documentation about this file and what it should contain.

2022-02-04 18:56 UTC, jsf9k commented
> Failing test seems imputable to docker instance : '''2022-01-31T17:01:49.4122921Z fatal: [fedora32]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\nFailed to connect to bus: Host is down\n"}''' In the real world, Fedora 32 is systemd based. Either ansible facts are wrong about systemd or the docker image have some ghosts information.

I think Fedora 32 lacks the ClamAV SystemD service that is being manipulated in this role, even though it does run SystemD.

2022-02-14 13:47 UTC, ClementJ35 commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
I did the changes mentioned above in [e485997](https://github.com/cisagov/ansible-role-clamav/pull/39/commits/e4859970e9b3a4cbaa125b75501620b9e038f4ac).
Can you check it's all right ?

2022-02-14 15:13 UTC, jsf9k commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
Looks good to me.  Thanks for making the changes.  @dav3r and @mcdonnnj, can you guys take another look?

2022-02-14 15:13 UTC, jsf9k approved these changes
Thanks for simplifying this Ansible role!

2022-02-14 16:19 UTC, dav3r approved these changes
This looks great to me now! 👍 👍

2022-02-14 16:20 UTC, dav3r commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
I'm satisfied with the recent changes for this - thanks.

2022-02-15 22:15 UTC, mcdonnnj commented on tasks/main.yml
> +  ansible.builtin.include_tasks: setup_bin.yml
The updates work for me as well.

2022-02-15 22:17 UTC, mcdonnnj approved these changes
Strong work! 💪💪💪

2022-02-16 14:53 UTC, merged