Selinux rules
cisagov/ansible-role-clamav pull request #63
Opened 2023-02-09 12:54 UTC by mjourdan

#  #

## 🗣 Description ##

This PR installs Selinux authorization.

## 💭 Motivation and context ##

This closes #62 

## 🧪 Testing ##

Following the procedure given in #62 

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-02-09 15:39 UTC, jsf9k requested changes
Here are a few minor things to get started.  I will look into the failing tests.

2023-02-09 15:39 UTC, jsf9k commented on tasks/main.yml
> +
Remove needless blank line:
```suggestion
```

2023-02-09 15:39 UTC, jsf9k commented on tasks/main.yml
> +    ansible.builtin.shell: semodule -i freshclam.pp
Prefer long form options for readability:
```suggestion
    ansible.builtin.shell: semodule --install freshclam.pp
```

2023-02-09 15:46 UTC, jsf9k requested changes
More minor things.

2023-02-09 15:46 UTC, jsf9k commented on tasks/main.yml
> +- name: selinux
The name of this block should be improved.  How about `Configure SELinux to allow freshclam downloads`?

2023-02-09 15:46 UTC, jsf9k commented on tasks/main.yml
> +  - name: Generate selinux policy for freshclam
```suggestion
  - name: Generate SELinux policy for freshclam
```

2023-02-09 15:46 UTC, jsf9k commented on tasks/main.yml
> +  - name: Apply selinux policy for freshclam
```suggestion
  - name: Apply SELinux policy for freshclam
```

2023-02-09 15:46 UTC, jsf9k commented on tasks/main.yml
> +  - name: Set selinux antivirus_can_scan_system flag persistently
```suggestion
  - name: Set SELinux antivirus_can_scan_system flag persistently
```

2023-02-09 15:46 UTC, jsf9k commented on tasks/main.yml
> +      persistent: yes
Alphabetize:
```suggestion
      name: antivirus_can_scan_system
      persistent: yes
      state: yes
```

2023-02-13 14:58 UTC, jsf9k commented on tasks/main.yml
> +- name: selinux
Resolved via commit f34d0bb.

2023-02-14 22:23 UTC, jsf9k commented
I spent a lot of time thinking about how to make the SELinux policy changes that you are adding in a clean way that passes `ansible-lint`.  After that I started to wonder why this change is necessary in the first place.

The problem is that [the SELinux policy for `freshclam`](https://github.com/fedora-selinux/selinux-policy/blob/f37/policy/modules/contrib/clamav.te) is [only allowing the standard HTTP port](https://github.com/fedora-selinux/selinux-policy/blob/f37/policy/modules/contrib/clamav.te#L232-L234).  You are trying to connect to a private mirror on port `8000`, which is in violation of this policy.

I think the answer here is to either 
- Make the changes to the SELinux policy that are required for your local environment (i.e., allow `freshclam` to reach out on port `8000`) _outside_ of this Ansible role
- Or, have your local ClamAV mirror start listening on port `80`

In any event, I don't think these changes belong in this Ansible role.  This Ansible role is intended to install and configure ClamAV, but it cannot support generic tweaking of the SELinux policy for your local environment; such support belongs, perhaps, in a locale-specific Ansible role.

If you feel differently, feel free to fork this repo and create your own version of this Ansible tole.

2023-02-14 22:23 UTC, closed without merging

2023-02-20 17:00 UTC, mjourdan commented
Having clamav to work with a private mirror listening on its default port sounded like a common-enough use-case to me, so I figured I would share my changes within this role.

Also there is a second part to this PR, where we [allow clamav to access the system](https://www.systutorials.com/docs/linux/man/8-antivirus_selinux/), which might be required on RedHat variants [according to clamavAV documentation](https://docs.clamav.net/manual/Usage/Configuration.html#configure-selinux-for-clamav).

Until we figure out a better approach, I think we'll keep using our fork for these tweaks. Anyway, thank you for the time you spent on this!

2023-02-21 18:35 UTC, jsf9k commented
> Also there is a second part to this PR, where we [allow clamav to access the system](https://www.systutorials.com/docs/linux/man/8-antivirus_selinux/), which might be required on RedHat variants [according to clamavAV documentation](https://docs.clamav.net/manual/Usage/Configuration.html#configure-selinux-for-clamav).

If you want to create a new PR that only includes this change that would be something we would include.