Add a custom cronjob functionnality
cisagov/ansible-role-clamav pull request #71
Opened 2023-10-12 07:56 UTC by ClementJ35

# Custom cronjob #

## 🗣 Description ##

This PR add a custom cronjob functionality, handle by Ansible variables dictionary.

## 💭 Motivation and context ##

Especially on Debian, cronjob are launch at the same time when we use cron keyword as daily. This is hard to sustain with an entire virtualization platform on which every scan start at the exact same time.

## 🧪 Testing ##

I tested on our virtual RedHat and Debian servers

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-10-12 08:53 UTC, ClementJ35 commented
Beware : This PR change the cron job behavior which can lead in two cron jobs both actives. The old one and the new one.

I don't know if the cleaning facility must be handled here.

2023-11-16 13:43 UTC, ClementJ35 commented
Hi,
Didn't have much news about this PR.
What do you think of it @jsf9k @mcdonnnj ?
And what about cleaning /etc/cron.*/virus_scan old files ?

IMO it should not be integrated here as it's a one shot, but it could be another little playbook related to this project.

2023-11-16 15:11 UTC, jsf9k requested changes
I'm sorry, this PR somehow fell off my radar.  I requested some minor cleanup changes, but overall this looks good to me.  Thank you for the contribution!

2023-11-16 15:11 UTC, jsf9k commented on defaults/main.yml
> +# Frequency of cronjob, must be one of "custom" or a special_time handled by ansible.builtin.cron
```suggestion
# Frequency of clamav cronjob, must be one of "custom" or a special_time handled by ansible.builtin.cron
```

2023-11-16 15:11 UTC, jsf9k commented on defaults/main.yml
> +# This dict doesn't merge, every line needs to be valuated:
```suggestion
# If clamav cronjob frequency is custom, the role uses this variable to install the cronjob.
# This dict doesn't merge, every line needs to be present.
```

2023-11-16 15:11 UTC, jsf9k commented on templates/virus_scan.sh.j2
> +# Beware : this script will be run by root
```suggestion
# Beware:  This script will be run by root.
```

2023-11-16 15:11 UTC, jsf9k commented on tasks/main.yml
> +    job: "/usr/local/share/virus_scan.sh"
The quotes are unnecessary here:
```suggestion
    job: /usr/local/share/virus_scan.sh
```

2023-11-16 15:11 UTC, jsf9k commented on molecule/default/tests/test_files_and_dirs.py
> +        # The virus scan shell
```suggestion
        # The virus scan shell script
```

2023-11-16 15:11 UTC, jsf9k commented on tasks/main.yml
> +- name: "Install virus_scan cron job as {{ clamav_cron_frequency }}"
Quotes are not necessary here:
```suggestion
- name: Install virus_scan cron job as {{ clamav_cron_frequency }}
```

2023-11-16 15:14 UTC, jsf9k commented
> Hi, Didn't have much news about this PR. What do you think of it @jsf9k @mcdonnnj ? And what about cleaning /etc/cron.*/virus_scan old files ?
> 
> IMO it should not be integrated here as it's a one shot, but it could be another little playbook related to this project.

Apologies, this PR somehow fell off my radar.  I don't think we need to worry about cleaning the old files, but if you want to create a separate playbook in an `extras` directory go ahead.

2023-11-17 10:24 UTC, ClementJ35 commented
I committed a little playbook to clean all cronjobs.
That's good to me.

2023-11-17 14:46 UTC, jsf9k requested changes
A few more minor language tweaks.

2023-11-17 14:46 UTC, jsf9k commented on tasks/main.yml
> +- name: "Install custom virus_scan cron job"
Remove unnecessary quotes:
```suggestion
- name: Install custom virus_scan cron job
```

2023-11-17 14:46 UTC, jsf9k commented on defaults/main.yml
> +# If clamav cronjob frequency is custom, the role uses this variable to install the cronjob.
```suggestion
# If clamav cronjob frequency is "custom", the role uses this variable to install the cronjob.
```

2023-11-17 14:46 UTC, jsf9k commented on defaults/main.yml
> +# Frequency of clamav cronjob, must be one of "custom" or a special_time handled by ansible.builtin.cron
```suggestion
# Frequency of clamav cronjob, must be "custom" or a special_time handled by ansible.builtin.cron
```

2023-11-17 14:46 UTC, jsf9k commented on defaults/main.yml
> +# This dict doesn't merge, every line needs to be present.
```suggestion
# This dict doesn't merge, so every line needs to be present.
```

2023-11-17 14:51 UTC, jsf9k commented
@ClementJ35 - When you accept someone's suggested changes, please change the commit message to something that describes the change.  Imagine someone who revisits these commits in the future; something like "Remove unnecessary quotes" will tell them much more about what changes the commit contains than "Apply suggestions from code review" or "Update defaults/main.yml".

2023-11-17 14:54 UTC, jsf9k approved these changes
Thank you for the contribution @ClementJ35!

2023-11-28 16:29 UTC, dav3r requested changes
I see one more thing that needs to be cleaned up here.

2023-11-28 16:29 UTC, dav3r commented on README.md
> +| clamav_cron_custom    | If frequency is set to custom a dictionnary define the timer. | `05:30` | No |
This cleans up the description, fixes a typo, and updates the correct default value.
```suggestion
| clamav_cron_custom    | If frequency is set to `custom`, a dictionary to define the timer. | `{"day": "*", "job": "/usr/local/share/virus_scan.sh", "minute": "30", "month": "*", "hour": "5", "weekday": "*"}` | No |
```

2023-12-15 15:30 UTC, dav3r approved these changes
👍 👍  Thanks for your contribution to this repo!

2023-12-19 18:33 UTC, jsf9k approved these changes

2023-12-19 18:33 UTC, merged

2023-12-19 18:33 UTC, jsf9k commented
Thanks for yet another contribution @ClementJ35!