Bugfix selinux dependency
cisagov/ansible-role-clamav pull request #72
Opened 2023-10-13 09:17 UTC by ClementJ35

# Bugfix: needed dependency for ansible.posix.seboolean #

The target needs to have python library to execute ansible.posix.seboolean as stated [here](https://docs.ansible.com/ansible/latest/collections/ansible/posix/seboolean_module.html#requirements).

This PR add the needed dependy as package to install for Fedora and RedHat (which are more likely to have selinux enabled)

2023-10-13 14:17 UTC, jsf9k commented on vars/Fedora.yml
> +# The ClamAV package names and the python lib to handle selinux
```suggestion
# The ClamAV package names, as well as the name of a Python package necessary to handle selinux
```

2023-10-13 14:19 UTC, jsf9k requested changes
I am requesting some minor changes.

2023-10-13 14:19 UTC, jsf9k commented on vars/Fedora.yml
>    - cronie
Alphabetize:
```suggestion
  # Later versions of Fedora do not come with a cron implementation
  # installed, but we need one.
  - cronie
  - python3-libsemanage
```

2023-10-13 14:19 UTC, jsf9k commented on vars/Fedora.yml
> +# The ClamAV package names and the python lib to handle selinux
```suggestion
# The ClamAV package names, as well as the name of a Python package necessary to handle selinux
```

2023-10-13 14:19 UTC, jsf9k commented on vars/Fedora_38.yml
> +# The ClamAV package names and the python lib to handle selinux
```suggestion
# The ClamAV package names, as well as the name of a Python package necessary to handle selinux
```

2023-10-13 14:19 UTC, jsf9k commented on vars/Fedora_38.yml
>    - cronie
Alphabetize:
```suggestion
  # Later versions of Fedora do not come with a cron implementation
  # installed, but we need one.
  - cronie
  - python3-libsemanage
```

2023-10-13 14:19 UTC, jsf9k commented on vars/RedHat.yml
> +# The ClamAV package names and the python lib to handle selinux
```suggestion
# The ClamAV package names, as well as the name of a Python package necessary to handle selinux
```

2023-11-21 16:04 UTC, jsf9k approved these changes
Thanks for the contribution @ClementJ35!

2023-11-21 16:17 UTC, dv4harr10 approved these changes

2023-11-21 16:17 UTC, merged